### ISSUE TITLE
为什么import进来打印出来是undefined

### ISSUE THREAD

**Issue by zhaozhuoboy** [huiyan-fe/mapv#102]
![image](https://user-images.githubusercontent.com/15223986/31993373-86421c1e-b9af-11e7-9d7c-4a6c48d0dbe0.png)

**Comment by zhaozhuoboy** [comment]
![image](https://user-images.githubusercontent.com/15223986/31993401-97193a04-b9af-11e7-9afd-cf6c4b211e50.png)

**Comment by LWH2017** [comment]
同问！！！

**Comment by zhaozhuoboy** [comment]
@LWH2017  要用命名导入  
```
import {DataSet,baiduMapLayer} from 'mapv';
```

**Comment by Michel-Yang** [comment]
按照上边的导入，报错找不到mapv
