### ISSUE TITLE
关于DEMO里用到的dataType是line

### ISSUE THREAD

**Issue by banterise** [huiyan-fe/mapv#11]
案例名称是polyline_simple_mofei
查看代码的时候发现当dataType是line的时候（关于line这个属性wiki里没有描述），
drawOptions内的lineWidth，globalCompositeOperation，strokeStyle这几个属性的设置都是无效的

小辈查看源代码后发现这三个属性都是静态的不支持传入参数的，略加修改后便可实现了

希望各位大神能在接下来的版本更新中修复这个问题并增加关于line这个datatype的相关描述。

万分感谢大神们开发出MAPV如此酷炫和高效的可视化产品！

**Comment by zmofei** [comment]
sorry， 这个是测试文件，误传到github上了，忽略这个文件吧
