### ISSUE TITLE
框架不兼容ie、edge

### ISSUE THREAD

**Issue by Lyule** [huiyan-fe/mapv#113]
IE、edge 下 使用baiduMapLayer 绘制图形的的事件报错

浏览器： ie 
![wechatimg45](https://user-images.githubusercontent.com/18359788/35609105-fa70cf5c-0696-11e8-8949-90415389a19a.jpeg)
![wechatimg46](https://user-images.githubusercontent.com/18359788/35609106-fcc4d744-0696-11e8-891d-915d351e80b8.jpeg)

附：demo
[mapv.zip](https://github.com/huiyan-fe/mapv/files/1680692/mapv.zip)

**Comment by Lyule** [comment]
ie, edge 不兼容算是很严重的bug了吧，百度大神 @hinikai , 求解决

**Comment by fuzhenn** [comment]
试着改了一下， 本地IE11/Edge都测试通过了

**Comment by fengyun2** [comment]
没有打包出来吧？看了源码好像还没变化。

**Comment by tom143tc** [comment]
别再给我发垃圾邮件了！！！！
在2018年05月09日 09:47，Royce 写道：

没有打包出来吧？看了源码好像还没变化。

**Comment by zhaozhe0831** [comment]
@tom143tc 你把 watch 取消了就不会收到了。自己点的 watch，还在这里怨别人。
