### ISSUE TITLE
jsp页面很容易崩溃

### ISSUE THREAD

**Issue by NYACC** [huiyan-fe/mapv#114]
从服务器接收数据,接收数据新增图层,同时使用destory方法 删除旧的图层,页面内存占用一直升,当多层多了的时候很容易崩溃.只有定时被动刷新页面,有其他更好的方法吗

**Comment by NYACC** [comment]
使用了destroy方法内存占用还是一直升,只有定时被动刷新页面,有其他更好的方法吗

**Comment by ykfDaMoWang** [comment]
我的情况是点图层增加、销毁很流畅，但是如果加入线图层，页面就会变得很卡~我现在是点的绘制用mapv，线的绘制用bmap，项目需求是能够满足了

**Comment by NYACC** [comment]
我自己建了一个池子,将对象放入里面循环使用,就不卡了.

**Comment by tom143tc** [comment]
我不知道你们是谁，别再给我发邮件了，谢谢！






在2018年02月8日 14:17，NYACC<notifications@github.com> 写道：

Closed #114.
