### ISSUE TITLE
请问能否增加更多的coordType选择呢

### ISSUE THREAD

**Issue by ShitMonkey** [huiyan-fe/mapv#12]
目前好像只支援百度经纬度及百度墨卡托坐标，暂时没有看到gcj02，wgs84这种常见经纬度的支援

**Comment by banterise** [comment]
自己编写了转换代码并整合到了源代码内部，目前已支援wgs84坐标系

**Comment by sy-tang** [comment]
@banterise 你是使用了API接口来转换么？

**Comment by hinikai** [comment]
@banterise 能分享下你的代码么
