### ISSUE TITLE
请教有没有对重叠的点求平均值，再画出来的库

### ISSUE THREAD

**Issue by deqoder** [huiyan-fe/mapv#132]
我采集了很多类似于“信号强度”的值，需要在地图上展示。
目前用热力图，但热力是把数据“加”起来，而不是求平均，导致一缩小，点叠加在一起，就全变红了。

也就是说，我需要能根据当前放大倍数，以及每个点的直径，来判断哪些点是重叠的，将重叠的点求平均合并成一个点再画出来。

如果百度地图没这样的库的话，请教其他gis有没有，用什么方便一点。

**Comment by hinikai** [comment]
感觉适合在数据层面先做好数据重叠点的聚合
