### ISSUE TITLE
关于引用maptalks的一些问题

### ISSUE THREAD

**Issue by geekeryoung** [huiyan-fe/mapv#135]
1、使用npm install安装以后会报 `Module not found: Can't resolve 'maptalks'` 这个错误。
2、手动引入maptalks0.40.2版本(最新版本)打包不报错了，但是运行的时候会报一个类型错误
`TypeError: Super expression must either be null or a function, not undefined`，错误定位是在mapv.js:220行。
暂时的解决方案是引入maptalks的0.39.8版本，这个版本目前还没有发现问题。

**Comment by fuzhenn** [comment]
我会检查一下是什么问题

**Comment by fuzhenn** [comment]
看你的报错，应当是没有正常载入maptalks库造成的

0.40.2相比0.39.8，有个变化是 package.json 中:
`"module": "dist/maptalks.es.js"`
改为了：
`"module": "dist/maptalks.mjs"`
(mjs是es module的推荐后缀名）

不清楚是不是这个改动造成的。

另maptalks图层程序的判断不那么严密，可能是你这里npm install后报maptalks出错的原因。我刚提了个[PR](https://github.com/huiyan-fe/mapv/pull/137)，希望能解决你的问题

**Comment by fuzhenn** [comment]
看上去是webpack 4的bug。。相关的issue：
https://github.com/maptalks/maptalks.js/issues/693
https://github.com/webpack/webpack/issues/7032

我会在0.40.3里，先滚回`es.js`后缀，等webpack那个bug解决以后，再滚回`.mjs`后缀

**Comment by geekeryoung** [comment]
好的，非常感谢你的关注，等你更新以后我再试试。

**Comment by fuzhenn** [comment]
已经发布了0.40.3
https://github.com/maptalks/maptalks.js/releases/tag/v0.40.3
