### ISSUE TITLE
使用高德地图，针对官网样例baidu-map-polyline-time.html，无法显示效果

### ISSUE THREAD

**Issue by bestmilan** [huiyan-fe/mapv#139]
我使用高德地图，利用example里的代码做了调整，仿写官网样例baidu-map-polyline-time.html的效果，目前没有报错，但是没有效果（只显示地图页面，没有动态效果）。

**Comment by sakitam-fdd** [comment]
@bestmilan 能贴一下 jsfiddle，或者源码吗？

**Comment by bestmilan** [comment]
@sakitam-fdd 主要代码都是基于mapv的baidu-map-polyline-time.html，就是把百度的地图换为了高德的，mapv的方法改为了AMapLayer。
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>

    <style type="text/css">
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }

        #map {
            width: 100%;
            height: 100%;
        }
    </style>
</head>
<body>

<div id="map"></div>
<canvas id="canvas"></canvas>

<script type="text/javascript" src="http://apps.bdimg.com/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript" src="mapv.js"></script>
<script src="http://webapi.amap.com/maps?v=1.4.2&key=6cb85da518029607d421917b7ddeb94a"></script>
<script type="text/javascript">
    var map = new AMap.Map('map', {
        resizeEnable: true,
        zoom: 12,
        center: [114.321317, 30.598428],
        //mapStyle: 'amap://styles/dark'
    });

    $.get('data/wuhan-car', function (rs) {

        var data = [];
        var timeData = [];

        rs = rs.split("\n");
        console.log(rs.length);
        var maxLength = 0;
        for (var i = 0; i < rs.length; i++) {
            var item = rs[i].split(',');
            var coordinates = [];
            if (item.length > maxLength) {
                maxLength = item.length;
            }
            for (j = 0; j < item.length; j += 2) {
                coordinates.push([item[j], item[j + 1]]);
                timeData.push({
                    geometry: {
                        type: 'Point',
                        coordinates: [item[j], item[j + 1]]
                    },
                    count: 1,
                    time: j
                });
            }
            data.push({
                geometry: {
                    type: 'LineString',
                    coordinates: coordinates
                }
            });

        }

        var dataSet = new mapv.DataSet(data);

        var options = {
            strokeStyle: 'rgba(53,57,255,0.5)',
            coordType: 'bd09mc',
            // globalCompositeOperation: 'lighter',
            shadowColor: 'rgba(53,57,255,0.2)',
            shadowBlur: 3,
            lineWidth: 3.0,
            draw: 'simple'
        }

        var mapvLayer = new mapv.AMapLayer(map, dataSet, options);


        var dataSet = new mapv.DataSet(timeData);

        var options = {
            fillStyle: 'rgba(255, 250, 250, 0.2)',
            coordType: 'bd09mc',
            globalCompositeOperation: "lighter",
            size: 1.5,
            animation: {
                stepsRange: {
                    start: 0,
                    end: 100
                },
                trails: 3,
                duration: 5,
            },
            draw: 'simple'
        }

        var mapvLayer = new mapv.AMapLayer(map, dataSet, options);
    });


</script>

</body>
</html>

**Comment by bestmilan** [comment]
@sakitam-fdd 好的，多谢帅哥，麻烦你啦！

**Comment by sakitam-fdd** [comment]
@bestmilan ,需要对坐标进行一次转换，并且去掉配置中的 `coordType: 'bd09ll'`。

``` html
<script type="text/javascript">
  var map = new AMap.Map('map', {
    resizeEnable: true,
    zoom: 12,
    center: [114.321317, 30.598428],
    mapStyle: 'amap://styles/dark'
  });
  $.get('../data/wuhan-car', function (rs) {
    var data = [];
    var timeData = [];
    rs = rs.split("\n");
    console.log(rs.length);
    var maxLength = 0;
    for (var i = 0; i < rs.length; i++) {
      var item = rs[i].split(',');
      var coordinates = [];
      if (item.length > maxLength) {
        maxLength = item.length;
      }
      for (j = 0; j < item.length; j += 2) {
        var x = Number(item[j]) / 20037508.34 * 180;
        var y = Number(item[j + 1]) / 20037508.34 * 180;
        y = 180 / Math.PI * (2 * Math.atan(Math.exp(y * Math.PI / 180)) - Math.PI / 2);
        if (x == 0 || y == NaN) {
          continue;
        }
        coordinates.push([x, y]);
        timeData.push({
          geometry: {
            type: 'Point',
            coordinates: [x, y]
          }, count: 1, time: j});
      }
      data.push({geometry: {type: 'LineString', coordinates: coordinates}});
    }
    var dataSetLine = new mapv.DataSet(data);
    var optionsLine = {
      strokeStyle: 'rgba(53,57,255,0.5)',
      globalCompositeOperation: 'lighter',
      shadowColor: 'rgba(53,57,255,0.2)',
      shadowBlur: 3,
      lineWidth: 3.0,
      draw: 'simple'
    }
    var mapvLayerLine = new mapv.AMapLayer(map, dataSetLine, optionsLine);
    var dataSet = new mapv.DataSet(timeData);
    var options = {
      fillStyle: 'rgba(255, 250, 250, 0.2)',
      globalCompositeOperation: "lighter",
      size: 1.5,
      animation: {stepsRange: {start: 0, end: 100}, trails: 3, duration: 5,},
      draw: 'simple'
    }
    var mapvLayer = new mapv.AMapLayer(map, dataSet, options);
  }); </script>
```

**Comment by bestmilan** [comment]
@sakitam-fdd 已经好了，多谢
