### ISSUE TITLE
拖动地图的时候会出现图层被截断的问题

### ISSUE THREAD

**Issue by sy-tang** [huiyan-fe/mapv#15]
在拖动地图的时候会出现图层被截断的问题，如下图，停止拖拽后才会闪现剩余的部分
<img width="375" alt="qq20151127-1 2x" src="https://cloud.githubusercontent.com/assets/1843681/11441462/3a904c3e-9547-11e5-9389-e01f821989ff.png">
移动端和pc端都会出现，这个是百度地图的问题，还是mapv本身的实现有问题？亦或是浏览器本身的渲染问题？

**Comment by zmofei** [comment]
为了提高性能，我们在渲染的时候仅仅渲染当前屏幕可见范围内的图层。
当拖动的时候，实际上是对当前可见图层的移动，为了提高新能，在拖拽的过程中我们并没有打开“重绘机制”，这样就会看到可见区域外的“空白”部分。
当拖拽结束后，mapv会触发重绘机制，重绘可见区域的图案。
