### ISSUE TITLE
[开发建议]simple模式下的layer绘制能否提供类似label中的maxZoom以及minZoom属性呢？

### ISSUE THREAD

**Issue by hijiangtao** [huiyan-fe/mapv#16]
本人开发过程中想分层次显示同一区域不同层次下的不同layer，但是一起绘制就层层覆盖了；layer属性中在mapV.js中没有找到maxZoom的相关代码，请问最近是否会添加这一功能？或者有其他的区域收缩显示不同层详细数据的方法？
谢谢。

**Comment by sy-tang** [comment]
可以在外围加上相关的处理逻辑：根据不同的缩放尺度，对相应的layer进行show/hide处理

**Comment by hijiangtao** [comment]
谢谢，已经通过百度地图API获取boundary然后show/hide解决了。
