### ISSUE TITLE
mapV支持谷歌地图吗？

### ISSUE THREAD

**Issue by yezishen001** [huiyan-fe/mapv#163]
因为做外国的项目请问类库是否支持谷歌地图？

**Comment by 2250685378** [comment]
同求，是否支持ArcGIS 地图

**Comment by Junior2Ran** [comment]
现在版本的支持`baidu-map` `google-map` `amap` `leaflet-map` `maptalks` `openlayers`，可以参考 https://github.com/huiyan-fe/mapv/tree/master/src/map 来添加您自己的地图
