### ISSUE TITLE
请教一下本项目和echarts项目是啥关系？

### ISSUE THREAD

**Issue by yanzixiang** [huiyan-fe/mapv#18]
http://echarts.baidu.com/doc/example.html
看介绍上面，有好多功能都是重合的。
echarts的功能更多一些呢。
http://echarts.baidu.com/extension/BMap/doc/example.htm
http://echarts.baidu.com/doc/example/map14.html
lhttp://echarts.baidu.com/doc/example/map18.html
http://echarts.baidu.com/doc/example/map19.html

**Comment by zmofei** [comment]
echarts是图表，mapv则更侧重地图相关的大数据的展示
