### ISSUE TITLE
多次绘制时，如何请除之前已绘制的数据？

### ISSUE THREAD

**Issue by robinma** [huiyan-fe/mapv#2]
多次绘制数据时，发现绘画结果为多个数据的重叠效果，请问如何在绘制前清除，或是在插件内部把问题处理掉。

**Comment by zmofei** [comment]
找到图层的layer ， 执行 layer.setMapv(null)

**Comment by loveltyoic** [comment]
折线动画的例子中，执行layer.setMapv(null)后，线没了，但是动画的点还在
