### ISSUE TITLE
如果当前视角只有一个点聚合的时候

### ISSUE THREAD

**Issue by DaikonX** [huiyan-fe/mapv#239]
如果当前视角只有一个点聚合的时候，那个点聚合会变黑。
![image](https://user-images.githubusercontent.com/23475171/96856680-c4879c80-1490-11eb-87b4-5012863cd156.png)
有人遇到过这样的问题吗

**Comment by wanghyper** [comment]
只有一个点时会取gradient为1.0时的值

**Comment by DaikonX** [comment]
> 只有一个点时会取gradient为1.0时的值

`         gradient: { 0: '#9ef3f1', 1.0: '#12cac6' },`

代码里面已经设置了 1.0的值了

**Comment by DaikonX** [comment]
> 只有一个点时会取gradient为1.0时的值

大佬你咋不回复了。

看了代码这个index=NaN了
`Intensity.prototype.getImageData = function (value) {

    var imageData = this.paletteCtx.getImageData(0, 0, 256, 1).data;

    if (value === undefined) {
        return imageData;
    }

    var max = this.max;
    var min = this.min;

    if (value > max) {
        value = max;
    }

    if (value < min) {
        value = min;
    }
    var index = Math.floor((value - min) / (max - min) * (256 - 1)) * 4;

    return [imageData[index], imageData[index + 1], imageData[index + 2], imageData[index + 3]];
};`
视图里就一个点聚合的时候  最大和最小都是他
0/0 就NaN了

**Comment by wanghyper** [comment]
已修复，请在最新版验证
