### ISSUE TITLE
mapvgl 图层显示，隐藏问题

### ISSUE THREAD

**Issue by xiaogaofudao** [huiyan-fe/mapv#240]
mapvgl 图层显示，隐藏有api 吗。类似 mapv 的 show hide 方法。另外能否开源呢？

**Comment by xiaogaofudao** [comment]
@hinikai @hedongran

**Comment by xiaogaofudao** [comment]
@hinikai  刚发现发布了 beta83新版本。 view 新增了 show， hide 方法，经测试显示隐藏可用。发现一个bug。图层绑定的点击事件在view 不可见的时候还可以触发点击。希望在框架层修复

**Comment by xiaogaofudao** [comment]
另外就是 如果多 layer 图层复用 一个 view。是否可以在 layer 层也提供  show hide 方法呢。

**Comment by xiaogaofudao** [comment]
目前是 一个 layer 使用一个 新的 view。实现图层的显隐

**Comment by xiaogaofudao** [comment]
@hinikai 提个建议啊，能否提供类似 zooms: [10, 15] 这种配置。在限制的zoom 内，图层显示，超出范围隐藏，框架内部控制显隐

**Comment by xiaogaofudao** [comment]
@hinikai 
又发现view show hide 渲染bug。业务逻辑如下：
监听地图 zoomend 缩放事件。缩放完成，根据 zoom 进行 两个 view 的 显隐控制，频繁出现 view hide 之后还会显示，闪烁等问题
大佬期待你的回复

**Comment by Junior2Ran** [comment]
为了方便开发者提问与上报bug，我们新建了mapvgl的repo，后续欢迎到对应repo上提issue
1.图层hide后，触发点击事件的bug已收到，后续会修正
2.单独layer的hide和show方法，加入到排期中，后续开发
3.不建议使用多个view，会造成性能问题，建议先用layer.setData([])和layer.setData(data)的方式来显隐
4.zoomend事件是缩放结束后才触发，如果一直来回缩放可能会出现闪烁问题，建议用zooming事件
