### ISSUE TITLE
当options.draw === 'cluster' 时，调用dataSet.set()方法更新数据后，点聚合的图表不会更新

### ISSUE THREAD

**Issue by magicvr** [huiyan-fe/mapv#243]
已定位到问题，并尝试初步修正成功
bug位于mapv.js的6070行开始的if判断内；初步判断为，没有更新supercluster内的点就直接采用了supercluster中的聚合点数据；
目前尝试的修正如下：
在判断内的逻辑块增加load新的dataSet的点的逻辑；

if (self.options.draw === 'cluster' && (!self.options.maxClusterZoom || self.options.maxClusterZoom >= this.getZoom())) {

          this.supercluster.load(self.dataSet.get());

          ...（其余代码不变）
}

上述修正已经解决点聚合图不更新的问题。但是否会引发其他问题暂时未测试。仅供参考。

**Comment by wanghyper** [comment]
此问题已修复，请使用最新版本
