### ISSUE TITLE
点聚合point_cluster 存在问题

### ISSUE THREAD

**Issue by fltjzit** [huiyan-fe/mapv#38]
使用点聚合point_cluster 例子时，如果将数据点的权重即count设置为1时，如果对地图放大操作时，聚合点不再聚合后，单个的marker不会显示，请开发人员测试一下，该现象是否是bug？
![19](https://cloud.githubusercontent.com/assets/19768659/15813773/32c37762-2bf4-11e6-85ba-2236669eb6af.JPG)
![20](https://cloud.githubusercontent.com/assets/19768659/15813774/3369de2c-2bf4-11e6-90ab-f4a3504b9dac.JPG)
![17](https://cloud.githubusercontent.com/assets/19768659/15813782/52d6eeee-2bf4-11e6-8641-e110a88da6d3.JPG)
![18](https://cloud.githubusercontent.com/assets/19768659/15813783/52e73934-2bf4-11e6-884d-44a658848f58.JPG)

**Comment by zmofei** [comment]
你好，产生文件的数据能否提供一下，我检查一下

**Comment by fltjzit** [comment]
在 2016-06-06 15:01:58，"Mofei Zhu" <notifications@github.com> 写道：


你好，产生文件的数据能否提供一下，我检查一下

**Comment by fltjzit** [comment]
[海量点聚合示例.zip](https://github.com/huiyan-fe/mapv/files/299947/default.zip)

**Comment by fltjzit** [comment]
[点聚合.zip](https://github.com/huiyan-fe/mapv/files/299956/default.zip)
请使用点聚合.zip这个例子，这个例子数据跟截图保持一致！

**Comment by fltjzit** [comment]
请使用点聚合压缩文件中的例子，这个例子使用数据跟截图保持一致！







在 2016-06-06 15:01:58，"Mofei Zhu" <notifications@github.com> 写道：


你好，产生文件的数据能否提供一下，我检查一下

**Comment by zmofei** [comment]
抱歉，我检查了一下代码确实是有你提出的问题。

问题的原因是 我们没有限制气泡的最小大小，当地图放大到一定程度时候，数量为1的气泡变得十分的小（可能为0），此时虽然气泡仍然存在，但是由于太小人眼无法看到。

稍后的版本我会更新这个bug。

目前我提供了一份修改了该bug的附件，你可以尝试临时使用附件中的版本

[Mapv.js.zip](https://github.com/huiyan-fe/mapv/files/300273/Mapv.js.zip)

**Comment by fltjzit** [comment]
收到，谢谢！






在 2016-06-06 19:33:47，"Mofei Zhu" <notifications@github.com> 写道：


抱歉，我检查了一下代码确实是有你提出的问题。

问题的原因是 我们没有限制气泡的最小大小，当地图放大到一定程度时候，数量为1的气泡变得十分的小（可能为0），此时虽然气泡仍然存在，但是由于太小人眼无法看到。

稍后的版本我会更新这个bug。

目前我提供了一份修改了该bug的附件，你可以尝试临时使用附件中的版本

Mapv.js.zip
