### ISSUE TITLE
有几个问题请教一下

### ISSUE THREAD

**Issue by chris2go** [huiyan-fe/mapv#4]
有几个问题请教一下

1、在哪里调用编辑器mapvE?
 2、points_density_honeycomb下的label off失效；
 3、points_intensity的值域控件调整后，需要操作地图（缩放，平移等）才能生效；
 4、IE10和EDGE下不支持webgl?
 5、polygon_intensity的值域控件调整，地图没有反应；
 6、webgl除了支持simple，还支持choropleth等其它方式吗？

谢谢！

**Comment by chris2go** [comment]
1、在哪里调用编辑器mapvE?
2、points_density_honeycomb下的label off失效；
3、points_intensity的值域控件调整后，需要操作地图（缩放，平移等）才能生效；
4、IE10和EDGE下不支持webgl?
5、polygon_intensity的值域控件调整，地图没有反应；

谢谢！

**Comment by zmofei** [comment]
mapvE 在调试中，近期会公布地址

**Comment by hinikai** [comment]
感谢您提出的问题，
2、points_density_honeycomb下的label off失效；
已修复
3、points_intensity的值域控件调整后，需要操作地图（缩放，平移等）才能生效；
已修复
5、polygon_intensity的值域控件调整，地图没有反应；
已修复

4、IE10和EDGE下不支持webgl?
6、webgl除了支持simple，还支持choropleth等其它方式吗？
关于webgl目前还只支持simple，只是临时解决大数据量的展示性能问题，其他更多的展示功能还有待开发

**Comment by alex2wong** [comment]
我请问下，为嘛不管是基于百度地图的Echart 热力图，还是 您这款MapV在地图拖动的时候都有卡顿的存在。。是Canvas在拖动的时候需要不断重绘吗，不是很懂canvas的渲染。望指教

**Comment by zmofei** [comment]
Canvas 在拖动结束之后，会重新绘制，取决于数据量，如果需要绘制的点比较多的话，在拖动结束，重绘热力图层的过程可能需要一些时间，所以造成了卡顿的感觉，后续根据实际反映情况，我们可能会尝试优化这个过程。

**Comment by chris2go** [comment]
补充个问题：所有类似intensity的值域调节控件，“上面”的bar拖动与“下面”的bar重合时，将不能复原

**Comment by zmofei** [comment]
感谢提问，问题已知晓，会尽快进行修复，修护完成后会及时告知
