### ISSUE TITLE
关于绘制线热力图时，色彩始终在较小值区间的问题

### ISSUE THREAD

**Issue by mirari** [huiyan-fe/mapv#44]
做线热力图的时候遇到一个坑，折腾了半天才发现问题所在，分享一下以免后人走弯路。

首先，线热力图的绘制流程是：
1.绘制折线，每条线都会根据count权重、max最大值来决定这条线的globalAlpha透明度。
比如count是9，max是10，全局透明度就是0.9。
2.取出整个画布，逐像素根据其透明度确定该像素的色彩。
比如透明度是0.9，配置项的色彩区间是红色，那么就会按红色渲染该像素。

但是，最大的坑就是，globalAlpha并非最终画布上像素的透明度。示例的配置项上还有一句`strokeStyle: 'rgba(0, 0, 0, 0.2)'`，这句话的效果就是，线条会采用透明度为0.2的黑色绘制。也就是说，在线条不重合的情况下，这条线在画布上的像素透明度应该是0.2*0.9=0.18。
示例上的线路应该有至少4条以上的重合，所以才看到了不少红色区块。但是我所用的数据源是几乎不重合的线网，希望通过权重来展现色彩差异，因为这个缘故，结果没有一条线的透明度超过0.4，所以呈现的效果就是几乎所有的线都是最低区段的颜色，无论其权重是否接近最大值。

如果你的情况与我类似，理想的配置项应该是类似这样的：

```
drawOptions: {
                blur: true, // 是否有模糊效果
                shadowBlur: 20,
                shadowColor: 'black',
                max: 10, // 设置显示的权重最大值
                lineWidth: 5, // 半径大小
                strokeStyle: 'rgba(0, 0, 0, 1)',
                maxOpacity: 0.8,//最终透明度
                gradient: { // 显示的颜色渐变范围
                    '0': 'blue',
                    '0.2': 'cyan',
                    '0.5': 'lime',
                    '0.7': 'yellow',
                    '1': 'red'
                }
            }
```

确保strokeStyle的透明度为1，这样每条线在不重合的情况下才能根据权重与最大值的比值正确显示其区段颜色。
maxOpacity是最终图层输出的透明度，如果一条线渲染结果是红色的，这里最终输出就是0.8透明度的红色。

**Comment by zmofei** [comment]
你用的是默认版本还是我们的v2版本的？

**Comment by mirari** [comment]
@zmofei master就是默认版本吧，我用的是master最新版

**Comment by zmofei** [comment]
@mirari 我看了一下，理论上strokeStyle的参数rgba中，只有a对于最终展示的效果有明显的作用，后面会考虑把这个参数的名称，和值的类型规范一下（比如叫 drawAlpha 范围是 0.01-1.00）。 谢谢你的反馈
