### ISSUE TITLE
补充几个问题

### ISSUE THREAD

**Issue by chris2go** [huiyan-fe/mapv#5]
补充几个问题：

1、所有类似intensity的值域调节控件，“上面”的bar拖动与“下面”的bar重合时，将不能复原

2、drawTypeControl可否调节位置，两种图叠加的时候，图例就重合了

3、cluster的drawOptions里面试了好几个属性都无效？包括颜色什么的

4、intensity里面linewidth只能作用于最后一个polygon；

5、choropleth的值域控件出来的效果，跟设置的splitlist有时候不一致；

谢谢！

**Comment by zmofei** [comment]
感谢提问，问题已知晓，会尽快进行修复，修护完成后会及时告知

**Comment by zmofei** [comment]
部分修复结果如下：

1. 上下bar重合之后，再次点击，用为重合有可能点击的是下边的bar，尝试反方向移动，即可。

3. cluster进行了修改，已经支持如下参数
```
{
    size: 60, // 网格大小
    unit: 'px', // 单位
    fillStyle: '#fa8b2e', // 填充颜色
    strokeStyle: '#fff', // 边框颜色
    label: { // 是否显示文字标签
        show: true,
    }
}
```

**Comment by hinikai** [comment]
感谢提出bug
4、intensity里面linewidth只能作用于最后一个polygon；
已经加上stroke功能

5、choropleth的值域控件出来的效果，跟设置的splitlist有时候不一致；
这个一直还没有复现，能帮提供更详细的信息么

**Comment by zmofei** [comment]
@chris2go 你之前问的编辑器已经上线 http://huiyan.baidu.com/mapv/

by the way 我自己分享的一个地址作为参考

http://huiyan.baidu.com/mapv/?user=zmofei&project=icq0dfuu_8kcd89
