### ISSUE TITLE
请问这是基于最新的百度地图api么

### ISSUE THREAD

**Issue by SharpFu** [huiyan-fe/mapv#54]
在最新的百度地图api中，关于subway，能看到成都地铁最新开放的地铁3号线，但是在mapv里面，始终没有3号线，最近项目在使用，求解!!!!!!

**Comment by SharpFu** [comment]
经过测试，当添加了样式后，即便为空样式，3号线就不见了，其他的线路都正常，注释掉这段代码后，3号线就出现了，一切都正常。请问是成都地铁3号线的数据有问题么？
map.setMapStyle({
    styleJson: []
});

**Comment by hinikai** [comment]
感谢您的关注，个性化底图数据是单独一套数据，我们这边会跟进处理下

**Comment by hinikai** [comment]
这个现已修复，谢谢~
