### ISSUE TITLE
v2版存在作用域污染

### ISSUE THREAD

**Issue by mirari** [huiyan-fe/mapv#56]
第1002行
` var pixel = map.pointToPixel(new BMap.Point(coordinate[j][0], coordinate[j][1]));`
在例子中运行正常是因为map是全局变量，如果例子中新建的map实例改成任意其他名字都会导致初始化报错：mapv.js:1002 Uncaught TypeError: map.pointToPixel is not a function

**Comment by hinikai** [comment]
感谢您发现问题，现在最新版本已经修复
