### ISSUE TITLE
v2版的蜂窝图或网格图，要如何在中央显示文字标签？

### ISSUE THREAD

**Issue by mirari** [huiyan-fe/mapv#58]
旧版的蜂窝图中央有累加的权重数字，新版我在文档中没找到显示文本的地方，而且无法跟网格联动，感觉只有颜色变化的视觉呈现太单调了。希望能补上这个功能。

**Comment by hinikai** [comment]
您好，目前可以通过在options中加showText:true参数来展示它累加的权重数字

**Comment by mirari** [comment]
@hinikai 我试了一下，现在只有grid可以显示文字，honeycomb仍然没有这个功能。而且文字的效果不是很理想，没有居中，能优化一下吗
