### ISSUE TITLE
开发计划

### ISSUE THREAD

**Issue by hinikai** [huiyan-fe/mapv#6]
### 9月25日
- [ ] 点动画
- [x] 线动画，按时间来展示
- [x] 线按热力图展示

### 其他计划
- [ ] 行政区域，详细demo
- [ ] 时间轴面板开发
- [ ] 线动画功能，移动动画效果
- [ ] 数据格式支持geojson
- [ ] 图例组件优化

### 2015年9月18日
- [x] 构建工具改为gulp

### 其他计划
- [x] 引入es6

## 3d：
- [ ] 地图
- [ ] 地球

### 9月25日
- [x] 官网开发上线，banner动画
- [x] 示例在线页面开发上线

### 10月15日
- [x] h5页面

### 编辑器优化
- [ ] 编辑器优化
- [ ] 编辑器显示数量

**Comment by zmofei** [comment]
2015年09月24日新增
- [ ] 教程细化

**Comment by zmofei** [comment]
此计划由于存在滞后性，暂时先关闭
