### ISSUE TITLE
Layer事件回调参数增加原始事件对象

### ISSUE THREAD

**Issue by kpaxqin** [huiyan-fe/mapv#60]
目前图层的click回调只有data参数：

```js
self.options.methods.click(data[i]);
```

代码：https://github.com/huiyan-fe/mapv/blob/master/src/map/baidu-map/Layer.js#L82

假设需要在点击地图时向点击位置添加InfoWindow，同时InfoWindow的渲染需要data上的信息，当前的事件回调参数无法满足此需求，因拿不到点击发生的位置

解决此问题只需在回调中传出原始事件对象即可：

```js
self.options.methods.click(data[i], e);
```

**Comment by hinikai** [comment]
感谢、已merge

**Comment by kpaxqin** [comment]
响应这么迅速，非常感谢
