### ISSUE TITLE
mapvLayer.hide() 删除图层的问题

### ISSUE THREAD

**Issue by echozheng** [huiyan-fe/mapv#62]
首先是我的配置：
var options = {
                strokeStyle: 'rgba(255,0, 0, 1)', // 描边颜色
                lineWidth: 0.2, // 描边宽度
                globalAlpha: 0.7,
                gradient: { 0.25: "rgb(0,0,255)", 0.55: "rgb(0,255,0)", 0.85: "yellow", 1.0: "rgb(255,0,0)"}
                methods: {
                    click: function (item) {
                        alert("该栅格的人总数 = " + item.count);
                    }
                }
            }

我在地图上画了一个包含许多个矩形的图层，配置(options)中有一个添加了一个click事件。
当我使用 mapvLayer.hide()删除图层的时候，再次点击刚刚出现矩形的地方(现在无矩形),还是产生了单击事件。可见，mapvLayer.hide() 只是隐藏了图层，并没有真正的删除图层。
请问，这个怎么解决呢？
谢谢大家。

**Comment by hinikai** [comment]
可使用mapvLayer.destroy()方法
