### ISSUE TITLE
怎么向地图上的点添加点击事件呢？

### ISSUE THREAD

**Issue by songkailei** [huiyan-fe/mapv#64]
找到了~

**Comment by zhaozhe0831** [comment]
@songkailei 同求，在哪？

**Comment by hu382337381** [comment]
同求，我也想知道怎么加点击事件 @songkailei

**Comment by zhaozhe0831** [comment]
@hu382337381 
通过 options 添加。
![image](https://cloud.githubusercontent.com/assets/12945873/22146722/8fa89930-df40-11e6-9c61-4c9372742d3f.png)

**Comment by hu382337381** [comment]
@zhaozhe0831 谢谢解答，确实可以点击了

**Comment by 007Galen-Guo** [comment]
我在手机端的vue上无法触发事件

**Comment by xiaogaofudao** [comment]
@CodeRong-Guo  手机端可以触发点击事件吗
