### ISSUE TITLE
在webpack中使用echarts文件打包过大

### ISSUE THREAD

**Issue by banterise** [huiyan-fe/mapv#65]
实际打包后的bundle.js达到5.7M之巨,哪怕是按需引入也是同样的大小,请问具体是什么原因呢

**Comment by hinikai** [comment]
这个应该去echarts项目的issues中提问哈～

**Comment by JhoneLee** [comment]
本人生产环境配置 devtool: 'cheap-module-source-map' 后 7.5MB -> 911kb
