### ISSUE TITLE
有没有只显示中国地图的方法，还有baiduMapLayer和Layer是什么关系

### ISSUE THREAD

**Issue by tezml** [huiyan-fe/mapv#70]
为什么baiduMapLayer和Layer的用法不一样？

**Comment by ilalali** [comment]
同问，layer = new Mapv.Layer   和  var mapvLayer = new mapv.baiduMapLayer(map, dataSet, options);
有什么不一样，前者有类库吗？

**Comment by tezml** [comment]
同步一下状态。只显示中国可以通过http://mapv.baidu.com/examples/#baidu-map-polygon-clip.html这个例子实现，如果需要配合别的功能，可以和其他组件共用

**Comment by hinikai** [comment]
目前这个最新版都是用mapv.baiduMapLayer这个方法了， Mapv.Layer 是老版本的方法

**Comment by tezml** [comment]
建议把旧版的api都干掉，写个全面点的api,现在这个api，有很多功能可能用户都发觉不到，像我，很多功能都是靠查源码才发现的。

**Comment by hinikai** [comment]
好的、感谢您的建议~
