### ISSUE TITLE
var layer = new Mapv.Layer和 var mapvLayer = new mapv.baiduMapLayer(map, dataSet, options);的区别？

### ISSUE THREAD

**Issue by ilalali** [huiyan-fe/mapv#71]
var layer = new Mapv.Layer和 var mapvLayer = new mapv.baiduMapLayer(map, dataSet, options);的区别？
如何删除前者的layer图层。

**Comment by hinikai** [comment]
同https://github.com/huiyan-fe/mapv/issues/70
