### ISSUE TITLE
mapvLayer调用update()或者setOptions()重新设置options时报错Cannot read property 'draw' of undefined

### ISSUE THREAD

**Issue by lishaobobo** [huiyan-fe/mapv#76]
mapvLayer调用update()或者setOptions()重新设置options时报错Cannot read property 'draw' of undefined

**Comment by lishaobobo** [comment]
我用<script src="http://huiyan-fe.github.io/mapv/build/mapv.min.js"></script>这个下的版本就好了。楼主可以看看是哪里的问题。

**Comment by hinikai** [comment]
之前是两边没同步，现在更新了，谢谢
