### ISSUE TITLE
使用浏览器自带的缩放功能时绘制有问题

### ISSUE THREAD

**Issue by kaixinwai** [huiyan-fe/mapv#90]
使用浏览器自带的缩放功能（例如：ctrl/+, ctrl/-）时绘制有问题，感觉有时会有残留的图形没有清空，具体可见附件截图，本该在中国地图上的点，跑到海里去了。
![screencapture-mapv-baidu-examples-1501729005643](https://user-images.githubusercontent.com/1039887/28904049-d92a6276-783a-11e7-915d-af0de169a29c.png)

**Comment by caidaodumogu** [comment]
解决了吗

**Comment by kangaroo711** [comment]
同问
