### ISSUE TITLE
可以支持openlayers吗

### ISSUE THREAD

**Issue by dyh333** [huiyan-fe/mapv#91]
如题，如果不可以的话，如何与ol做结合的能否提供下思路，比如用ol加载底图，并用mapv绘制蜂巢图。谢谢。

**Comment by banterise** [comment]
自己改源代码吧老铁

**Comment by hinikai** [comment]
已经支持、可以看看示例下的openlayers

**Comment by lzp0070007** [comment]
目前只支持到4.6   我试了试 ol5  好像不支持

**Comment by pursuelu** [comment]
这个插件仅支持原生引入js的方式吧，插件里面对ol依赖，我多次尝试vue的导包均不可，但全部改成引入js的方式可以。

**Comment by mohong** [comment]
> 这个插件仅支持原生引入js的方式吧，插件里面对ol依赖，我多次尝试vue的导包均不可，但全部改成引入js的方式可以。

你试的可以用的ol是哪个版本的？

**Comment by pursuelu** [comment]
> > 这个插件仅支持原生引入js的方式吧，插件里面对ol依赖，我多次尝试vue的导包均不可，但全部改成引入js的方式可以。
> 
> 你试的可以用的ol是哪个版本的？

新版都可以，ol是引入js的方式，mapv是import导入的，就官网的ol示例可以跑
