### ISSUE TITLE
[BUG] vue项目中CanvasLayer初始化时找不到show方法

### ISSUE THREAD

**Issue by kdush** [huiyan-fe/mapv#93]
在vuecli创建的默认webpack项目中使用了vue-baidu-map创建了百度地图
然后在vue中创建图层失败,原因是CanvasLayer初始化的时候找不到自身的show属性
另外eslint 开启stand的时候  new mapv.baiduMapLayer 会报错,baiduMapLayer的B要求大写
@hinikai 大神求解答

```
<template>
  <div class="hello">
    <baidu-map class='bm-view' :scroll-wheel-zoom='true' @ready='handler'>
    </baidu-map>
  </div>
</template>

<script>
import Vue from 'vue'
import BaiduMap from 'vue-baidu-map'
import *as mapv from 'mapv'

Vue.use(BaiduMap, {
  ak: '1XjLLEhZhQNUzd93EjU5nOGQ'
})
export default {
  BmapObject: {},
  mapObj: {},
  data() {
    return {
      largeList: [
        [
          87.88153173,
          39.70716860135857
        ],
        [
          108.2684158354,
          25.354314
        ],
        [
          112.7061793635,
          37.5315
        ],
        [
          112.633886555,
          28.2816287171757
        ],
        [
          98.128777716606,
          32.8284638
        ],
        [
          109.3,
          39.60313523218775
        ],
        [
          97.445419148716,
          25.6012508613
        ],
        [
          97.6376312,
          29.89424201437
        ]]
    }
  },
  methods: {
    handler({ Bmap, map }) {
      this.mapObj = map
      this.BmapObject = Bmap


      let largeList = this.largeList
      let data = []
      for (var i = 0; i < largeList.length; i++) {
        data.push({
          geometry: {
            type: 'Point',
            coordinates: largeList[i]
          }
        })
      }
      
      let dataSet = new mapv.DataSet(data)
      let largePointOption = {
        fillStyle: 'rgba(200, 200, 0, 0.8)',
        bigData: 'Point',
        size: 0.7,
        draw: 'simple',
        zoom: this.zoom,
        center: this.center
      }
      console.log(map)
/**
       * @todo  CanvasLayer里面this.show 找不到,是作用域问题吗
       */
      let a = new mapv.baiduMapLayer(map, dataSet, largePointOption)
    }
  },
  mounted() {
    console.log(mapv)
  },

}

</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.bm-view {
  width: 100%;
  height: 1024px;
}

h1,
h2 {
  font-weight: normal;
}

ul {
  list-style-type: none;
  padding: 0;
}

li {
  display: inline-block;
  margin: 0 10px;
}

a {
  color: #42b983;
}
</style>
```

**Comment by kdush** [comment]
为了演示说明
我创建了一个项目 
[Demo实例](https://github.com/kdush/MapvBugDemo)

**Comment by zmofei** [comment]
查看了代码，发现`vue-baidu-map`的ready事件触发时，百度地图SDK的变量BMap还未在全局(window)中写入，而Mapv的某些操作是依赖于BMap的全局变量的，所以此时`new mapv.baiduMapLayer`就会因为找不到BMap报错。

建议把地图的SDK写入到html的head中

**Comment by zmofei** [comment]
Mapv在引入的时候，默认此时的BMap（地图SDK）是已经存在的，`vue-baidu-map`异步加载了地图的SDK导致在引入mapv时，全局的BMap并不存在，所以报错。
后续会针对异步加载的SDK进行优化，目前建议你先尝试把SDK在<head>中引入以临时解决问题。

**Comment by RLwu** [comment]
遇到了同样的问题，另”eslint 开启的时候 new mapv.baiduMapLayer 会报错,baiduMapLayer的B要求大写“什么时候更新呢？

**Comment by zhaozhe0831** [comment]
@RLwu 你这个问题是 eslint 的设置，跟 mapv 本身没关系。

**Comment by RLwu** [comment]
好吧，多谢，只能去配置eslint了。

**Comment by kdush** [comment]
改好了能否分享一下 最近好忙 没空去学读文档了


原始邮件
发件人:RL.wunotifications@github.com
收件人:huiyan-fe/mapvmapv@noreply.github.com
抄送:Ray Zhangzhangdaleigogo@qq.com; Mentionmention@noreply.github.com
发送时间:2017年8月17日(周四) 18:00
主题:Re: [huiyan-fe/mapv] [BUG] vue项目中CanvasLayer初始化时找不到show方法 (#93)


好吧，多谢，只能去配置eslint了。

**Comment by mythbobo** [comment]
想问一下。。这个问题到底怎么解决啊？也遇到一样的问题。

**Comment by Nioty** [comment]
相同的问题..

**Comment by keepstraight** [comment]
> 在vuecli创建的默认webpack项目中使用了vue-baidu-map创建了百度地图
> 然后在vue中创建图层失败,原因是CanvasLayer初始化的时候找不到自身的show属性
> 另外eslint 开启stand的时候 new mapv.baiduMapLayer 会报错,baiduMapLayer的B要求大写
> @hinikai 大神求解答
> 
> ```
> <template>
>   <div class="hello">
>     <baidu-map class='bm-view' :scroll-wheel-zoom='true' @ready='handler'>
>     </baidu-map>
>   </div>
> </template>
> 
> <script>
> import Vue from 'vue'
> import BaiduMap from 'vue-baidu-map'
> import *as mapv from 'mapv'
> 
> Vue.use(BaiduMap, {
>   ak: '1XjLLEhZhQNUzd93EjU5nOGQ'
> })
> export default {
>   BmapObject: {},
>   mapObj: {},
>   data() {
>     return {
>       largeList: [
>         [
>           87.88153173,
>           39.70716860135857
>         ],
>         [
>           108.2684158354,
>           25.354314
>         ],
>         [
>           112.7061793635,
>           37.5315
>         ],
>         [
>           112.633886555,
>           28.2816287171757
>         ],
>         [
>           98.128777716606,
>           32.8284638
>         ],
>         [
>           109.3,
>           39.60313523218775
>         ],
>         [
>           97.445419148716,
>           25.6012508613
>         ],
>         [
>           97.6376312,
>           29.89424201437
>         ]]
>     }
>   },
>   methods: {
>     handler({ Bmap, map }) {
>       this.mapObj = map
>       this.BmapObject = Bmap
> 
> 
>       let largeList = this.largeList
>       let data = []
>       for (var i = 0; i < largeList.length; i++) {
>         data.push({
>           geometry: {
>             type: 'Point',
>             coordinates: largeList[i]
>           }
>         })
>       }
>       
>       let dataSet = new mapv.DataSet(data)
>       let largePointOption = {
>         fillStyle: 'rgba(200, 200, 0, 0.8)',
>         bigData: 'Point',
>         size: 0.7,
>         draw: 'simple',
>         zoom: this.zoom,
>         center: this.center
>       }
>       console.log(map)
> /**
>        * @todo  CanvasLayer里面this.show 找不到,是作用域问题吗
>        */
>       let a = new mapv.baiduMapLayer(map, dataSet, largePointOption)
>     }
>   },
>   mounted() {
>     console.log(mapv)
>   },
> 
> }
> 
> </script>
> 
> 
> <style scoped>
> .bm-view {
>   width: 100%;
>   height: 1024px;
> }
> 
> h1,
> h2 {
>   font-weight: normal;
> }
> 
> ul {
>   list-style-type: none;
>   padding: 0;
> }
> 
> li {
>   display: inline-block;
>   margin: 0 10px;
> }
> 
> a {
>   color: #42b983;
> }
> </style>
> ```



> 改好了能否分享一下 最近好忙 没空去学读文档了 原始邮件 发件人:RL.wunotifications@github.com 收件人:huiyan-fe/mapvmapv@noreply.github.com 抄送:Ray Zhangzhangdaleigogo@qq.com; Mentionmention@noreply.github.com 发送时间:2017年8月17日(周四) 18:00 主题:Re: [huiyan-fe/mapv] [BUG] vue项目中CanvasLayer初始化时找不到show方法 (#93) 好吧，多谢，只能去配置eslint了。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

请问您这个问题解决了吗？？能分享一下解决办法吗？？

**Comment by keepstraight** [comment]
已经解决了，打扰了。
