### ISSUE TITLE
mapv和echarts定位有什么区别

### ISSUE THREAD

**Issue by fishergisdldt** [huiyan-fe/mapv#96]
两者有很大重复度，他们之间的区别是什么

**Comment by dfEric** [comment]
我认为主要是数据体现方式吧，echarts针对具体数据，mapv更倾向于展示一种大量数据下的趋势

**Comment by banterise** [comment]
一个属于EFE团队,一个属于慧眼团队,至于产品定位,mapv更专注地图部分,不过最近好像不太活跃了,似乎在酝酿着什么
